### ISSUE TITLE
commit message format

### ISSUE THREAD

**Issue by shana0440** [u-job/api-server#9]
Our commit message is not **consistency** for now.
@flamerecca using a part of [Angular git commit message rules](https://gist.github.com/stephenparish/9941e89d80e2bc58a153), But I don't.
The reason I not using the angular git commit message is I don't want to spend time to figure out I'm updating the `docs` or `chore` or something else, or spend time commit everything respectively, because of some time we will mix something together(or only I will 🙈), e.g. when I implement a new feature, I might do some refactoring related to this feature.

And one more thing, we have to add **issue number** at the end of the commit message, so we can figure out what is this PR or commit fix or implement what issue.

do you guys have any opinions? @flamerecca @kuotinyen

**Comment by shana0440** [comment]
> And one more thing, we have to add **issue number** at the end of the commit message, so we can figure out what is this PR or commit fix or implement what issue.

for example `commit message #1`

**Comment by flamerecca** [comment]
* issue number 
可以加上去沒問題，下次我會注意

* git commit message rules
這個目前我覺得可以不用統一，不過如果要統一不使用也可以

**Comment by shana0440** [comment]
@flamerecca 
I think we should better make its consistency, I prefer not to use `feat` or something else in front of the commit message if you ok with that, I will open a PR to add the commit message rule in README.

**Comment by kuotinyen** [comment]
I agree, but I'd like to know the commit example for add any feature, update anything, or fix something.
Can it just be: Add, Update, Fix?
Or I just wait for the PR to discuss, haha.

**Comment by shana0440** [comment]
In my opinion, the issue will tell us this PR is update, fix, or implement a new feature, so no need to add it in the commit message, but If you guys want to know about more in the commit message, it ok to add the `feat`, `update`, `fix` tag in front of commit message.

**Comment by kuotinyen** [comment]
Actually I don't like any comment before commit, 
"Add circleCI flow #1", 
this commit is ok for me, because "Add" give the meaning to "add  something".
Maybe after add ticket number might be:
"[#1] Add circleCI flow"?

**Comment by shana0440** [comment]
You point is this commit should talk what it did? like it updates something or add somthing?
and I prefer to add issue number at the end of the commit message, if it in front of the commit message, I can imagine it will really difficult to read.

**Comment by kuotinyen** [comment]
How about Using "Add circleCI flow" and add "#1" to description?

**Comment by shana0440** [comment]
I think 
```
Add CI configuration

Connect #1
```
is more readable.

**Comment by kuotinyen** [comment]
Can we use 
```
Add CI configuration

Connect to issue #1.
```

**Comment by shana0440** [comment]
@kuotinyen I'm ok,
@flamerecca any opinion?
